// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehwjqnqkodjpnjpygwfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVod2pxbnFrb2RqcG5qcHlnd2ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MjM5NTAsImV4cCI6MjA2MjI5OTk1MH0.D4cEf46aAZQyN7cQ76KDzSc3mjSX0iuOKtSRGNJYQGk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);